clients/urls.py
from django.urls import path
from clients.views import LoginClass,logout,CreateClass,EditClass,edit_password,crear_proyecto

app_name="client"
urlpatterns = [
    path('login/',LoginClass.as_view(),name="login"),
    path('logout/',logout,name="logout"),
    path('create/',CreateClass.as_view(),name="create"),
    path('edit/',EditClass.as_view(),name="edit"),
    path('edit_password/',edit_password,name="edit_password"),
    path('create_project/',crear_proyecto,name="create_project")

    
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from portfolio.views import error_404
from .views import listar_proyectos 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', listar_proyectos,name="home"),
    path('admin/', admin.site.urls),
    path('clients/', include('clients.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = error_404

templates/bases/base_admin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{%block title%} {%endblock%}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" type= "text/css" href="{% static 'css/style.css'%}">
    {%block scripts %} {%endblock%}
    
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <img src={% static "images/logo.png" %} alt="logo">
          <a class="navbar-brand" href="{% url 'home' %}">Home</a>          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse ms-auto" id="navbarNavAltMarkup">
            <div class="navbar-nav ms-auto">
              {% if not user.is_authenticated %}
              <a class="nav-link" href="{% url 'client:login'%}">Iniciar Sesión</a>
              <a class="nav-link active" href="{% url 'client:create'%}"aria-current="true">Registrate!</a>
              </div>
              {% endif %} 
              {% if user.is_authenticated %}
              <div class="collapse navbar-collapse ms-auto" id="navbarNavAltMarkup" style="margin-bottom:15px;">
                <div class="navbar-nav ms-auto">
                <a class="nav-link" href="{% url 'client:create_project'%}">Crear Proyecto</a>
                <a class="nav-link" href="{% url 'client:edit'%}">Editar Datos</a>
                <a class="nav-link" href="{% url 'client:edit_password'%}">Editar Contraseña</a>                
                <a class="nav-link" href="{% url 'client:logout'%}">Cerrar Sesión</a>
                </div>
                {% endif %} 
          </div>
        </div>
    </nav>
    
    {%if messages%}
        <div class="center-align">
            <ul class= "messages">
                {%for message in messages%} 
                <li {%if message.tags%} class = '{{message.tags}}_message'{%endif%}>{{message}}</li>
                {%endfor%}
            <ul>
        </div>
    {%endif%}

    {%block content %}{% endblock %}
    
    {%block footer %}{% endblock %}

</body>
</html>